[env:esp32s3-devkitc]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit MLX90640 @ ^1.1.1
    adafruit/Adafruit BusIO @ ^1.16.1
