[platformio]
default_envs = esp32s3-devkitc

[env:esp32s3-devkitc]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -std=gnu++17

build_unflags = -std=gnu++11

lib_deps =
    bolderflight/Bolder Flight Systems MPU9250 @ ^1.0.2
    adafruit/Adafruit MLX90640 @ ^1.1.1
    adafruit/Adafruit BusIO @ ^1.16.1
    kosme/arduinoFFT @ ^2.0.4
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.2.0
